# Uncomment this line to define a global platform for your project
platform :ios, '10.0'


target 'Module_B_Category' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod "ZWJ_CTMediator", :path => '../ZWJ_CTMediator'
 
end

