# Uncomment this line to define a global platform for your project
platform :ios, '10.0'


target 'Module_A' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod "ZWJ_CTMediator", :path => "../ZWJ_CTMediator"
  pod "ZWJ_MasonyFrame", :path => "../ZWJ_MasonyFrame"
  pod "Module_B_Category", :path => "../Module_B_Category"
 
end
