# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Module_A_Category' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Module_A_Category
	pod "ZWJ_CTMediator", :path => '../ZWJ_CTMediator'

end
