# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Module_B' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "ZWJ_MasonyFrame", :path => "../ZWJ_MasonyFrame"

end
